name: C Build and Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get install -y gcc

      - name: Build the program
        run: gcc -o hello hello.c

      - name: Run the program
        run: ./hello
